version: "3.8"
services:
  db:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass!
      POSTGRES_DB: blogai
    ports:
      - "6543:5432"
  # pgadmin:
  #   container_name: pgadmin_container
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: Penisbutt123!
  #   ports:
  #     - "5050:80"

#   version: "3.8"
# services:
#   db:
#     image: postgres
#     environment:
#       POSTGRES_DB: ${DB_NAME:-postgres}
#       POSTGRES_USER: ${DB_USER:-postgres}
#       POSTGRES_PASSWORD: ${DB_PASSWORD:-mysecretpassword}
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
# volumes:
#   postgres_data:

